version: "3.9"

services:
  database:
    image: postgres
    container_name: database_engeman
    restart: "always"
    ports: 
    - 5432:5432
    environment:
      - POSTGRES_USER=engeman
      - POSTGRES_PASSWORD=engemandb
      - POSTGRES_DB=engemanapi
    volumes:
      - pgdata:/data/postgres

  app:
    build: .
    container_name: engemanapi
    restart: "always"
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - database
    depends_on:
      - database

volumes:
  pgdata:
    driver: local
    
    
