version: "3.9"

services:
  database:
    image: postgres
    container_name: database_easyjob
    restart: "always"
    ports: 
    - 5432:5432
    environment:
      - POSTGRES_USER=easyjob
      - POSTGRES_PASSWORD=easyjobdb
      - POSTGRES_DB=easyjobapi
    volumes:
      - pgdata:/data/postgres

  app:
    build: .
    container_name: easyjobapi
    restart: "always"
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - database
    depends_on:
      - database

volumes:
  pgdata:
    driver: local
    
    
